SET(SOURCES ui_scrMain.c
    ui_scrPanelSettings.c
    ui_scrWallpaper.c
    ui_scrInit.c
    ui_scrCalibration.c
    ui_scrDimsandSensorsandWaters.c
    ui_scrSettings.c
    ui_scrRGB.c
    ui_scrTheme.c
    ui_scrPages.c
    ui.c
    ui_comp_hook.c
    ui_helpers.c
    ui_events.c
    ui_img_logo3_png.c
    ui_img_1542361832.c
    ui_img_btconnected_png.c
    ui_img_sconnected_png.c
    ui_img_snotconnected_png.c
    ui_img_btnotconnected_png.c
    ui_img_weatherforecast2_png.c
    ui_img_button_up_png.c
    ui_img_button_down_png.c
    ui_img_caravan_logo_png.c
    ui_img_ac_png.c
    ui_img_heater_png.c
    ui_img_lamp_png.c
    ui_img_outlet_png.c
    ui_img_oven_png.c
    ui_img_readinglamp_png.c
    ui_img_refrigerator_png.c
    ui_img_toilet_png.c
    ui_img_tv_png.c
    ui_img_usb_png.c
    ui_img_water_png.c
    ui_img_1096609443.c
    ui_img_sliderpassive_png.c
    ui_img_slideractivee_png.c
    ui_img_arcdesign2_png.c
    ui_img_arcdesign_png.c
    ui_img_tempicon_png.c
    ui_img_outcontrols_png.c
    ui_img_theme_png.c
    ui_img_connectioncontrol_png.c
    ui_img_calibration_png.c
    ui_img_btnsettings2_png.c
    ui_img_sensors_png.c
    ui_img_waterlevel_png.c
    ui_img_rgbcontrol_png.c
    ui_img_settingsicon_png.c)

add_library(ui ${SOURCES})
