// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_scrMain.h"
#include "ui_scrPanelSettings.h"
#include "ui_scrWallpaper.h"
#include "ui_scrInit.h"
#include "ui_scrCalibration.h"
#include "ui_scrDimsandSensorsandWaters.h"
#include "ui_scrSettings.h"
#include "ui_scrRGB.h"
#include "ui_scrTheme.h"
#include "ui_scrPages.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * commScreen_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo3_png);    // assets/logo3.png
LV_IMG_DECLARE(ui_img_1542361832);    // assets/New Project (1).png
LV_IMG_DECLARE(ui_img_btconnected_png);    // assets/btconnected.png
LV_IMG_DECLARE(ui_img_sconnected_png);    // assets/sconnected.png
LV_IMG_DECLARE(ui_img_snotconnected_png);    // assets/snotconnected.png
LV_IMG_DECLARE(ui_img_btnotconnected_png);    // assets/btnotconnected.png
LV_IMG_DECLARE(ui_img_weatherforecast2_png);    // assets/weatherforecast2.png
LV_IMG_DECLARE(ui_img_button_up_png);    // assets/button up.png
LV_IMG_DECLARE(ui_img_button_down_png);    // assets/button down.png
LV_IMG_DECLARE(ui_img_caravan_logo_png);    // assets/caravan logo.png
LV_IMG_DECLARE(ui_img_ac_png);    // assets/AC.png
LV_IMG_DECLARE(ui_img_heater_png);    // assets/heater.png
LV_IMG_DECLARE(ui_img_lamp_png);    // assets/lamp.png
LV_IMG_DECLARE(ui_img_outlet_png);    // assets/outlet.png
LV_IMG_DECLARE(ui_img_oven_png);    // assets/oven.png
LV_IMG_DECLARE(ui_img_readinglamp_png);    // assets/readinglamp.png
LV_IMG_DECLARE(ui_img_refrigerator_png);    // assets/refrigerator.png
LV_IMG_DECLARE(ui_img_toilet_png);    // assets/toilet.png
LV_IMG_DECLARE(ui_img_tv_png);    // assets/tv.png
LV_IMG_DECLARE(ui_img_usb_png);    // assets/usb.png
LV_IMG_DECLARE(ui_img_water_png);    // assets/water.png
LV_IMG_DECLARE(ui_img_1096609443);    // assets/connstatusıcons.png
LV_IMG_DECLARE(ui_img_sliderpassive_png);    // assets/sliderpassive.png
LV_IMG_DECLARE(ui_img_slideractivee_png);    // assets/slideractivee.png
LV_IMG_DECLARE(ui_img_arcdesign2_png);    // assets/arcdesign2.png
LV_IMG_DECLARE(ui_img_arcdesign_png);    // assets/arcdesign.png
LV_IMG_DECLARE(ui_img_tempicon_png);    // assets/tempicon.png
LV_IMG_DECLARE(ui_img_outcontrols_png);    // assets/outcontrols.png
LV_IMG_DECLARE(ui_img_theme_png);    // assets/theme.png
LV_IMG_DECLARE(ui_img_connectioncontrol_png);    // assets/connectioncontrol.png
LV_IMG_DECLARE(ui_img_calibration_png);    // assets/calibration.png
LV_IMG_DECLARE(ui_img_btnsettings2_png);    // assets/btnSettings2.png
LV_IMG_DECLARE(ui_img_sensors_png);    // assets/sensors.png
LV_IMG_DECLARE(ui_img_waterlevel_png);    // assets/waterlevel.png
LV_IMG_DECLARE(ui_img_rgbcontrol_png);    // assets/rgbcontrol.png
LV_IMG_DECLARE(ui_img_settingsicon_png);    // assets/settingsicon.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
