// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void slMutfakValueChanged(lv_event_t * e)
{
	// Your code here
}

void arcTemizSuValueChanged(lv_event_t * e)
{
	// Your code here
}

void out1Event(lv_event_t * e)
{
	// Your code here
}

void Out2Event(lv_event_t * e)
{
	// Your code here
}

void Out3Event(lv_event_t * e)
{
	// Your code here
}

void Out4Event(lv_event_t * e)
{
	// Your code here
}

void Out5Event(lv_event_t * e)
{
	// Your code here
}

void Out6Event(lv_event_t * e)
{
	// Your code here
}

void Out7Event(lv_event_t * e)
{
	// Your code here
}

void Out8Event(lv_event_t * e)
{
	// Your code here
}

void turnThemeWhite(lv_event_t * e)
{
	// Your code here
}

void btnThemeWhiteFunc(lv_event_t * e)
{
	// Your code here
}

void btnBlackThemeFunc(lv_event_t * e)
{
	// Your code here
}

void denemezartzurt(lv_event_t * e)
{
	// Your code here
}

void savePanelSettings(lv_event_t * e)
{
	// Your code here
}

void btnSaveThemeEvent(lv_event_t * e)
{
	// Your code here
}

void btnSaveThemeFunc(lv_event_t * e)
{
	// Your code here
}

void changeColorWheel(lv_event_t * e)
{
	// Your code here
}

void applyRGBColor(lv_event_t * e)
{
	// Your code here
}

void setrgbToWhite(lv_event_t * e)
{
	// Your code here
}

void enRGBSetWhiteFunc(lv_event_t * e)
{
	// Your code here
}

void enRGBTurnONFunc(lv_event_t * e)
{
	// Your code here
}

void enRGBTurnOFFFunc(lv_event_t * e)
{
	// Your code here
}

void btnDimsCallbackFunc(lv_event_t * e)
{
	// Your code here
}

void btnOutputsCallbackFunc(lv_event_t * e)
{
	// Your code here
}

void btnTemperaturesCallbackFunc(lv_event_t * e)
{
	// Your code here
}

void btnWatersCallbackFunc(lv_event_t * e)
{
	// Your code here
}

void btnReturnfromscrDimsandSensorstoscrMainCallback(lv_event_t * e)
{
	// Your code here
}

void sldBrightnessAdjustCallback(lv_event_t * e)
{
	// Your code here
}
