// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_scrWallpaper = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_btnUnlockScreen = NULL;
// event funtions
void ui_event_btnUnlockScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_scrMain_screen_init);
    }
}

// build funtions

void ui_scrWallpaper_screen_init(void)
{
    ui_scrWallpaper = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrWallpaper, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrWallpaper, lv_color_hex(0x317E94), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrWallpaper, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_scrWallpaper);
    lv_img_set_src(ui_Image3, &ui_img_caravan_logo_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -5);
    lv_obj_set_y(ui_Image3, -15);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_scrWallpaper);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -8);
    lv_obj_set_y(ui_Label3, 164);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "HEXNET TECHNOLOGY");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnUnlockScreen = lv_btn_create(ui_scrWallpaper);
    lv_obj_set_width(ui_btnUnlockScreen, 711);
    lv_obj_set_height(ui_btnUnlockScreen, 377);
    lv_obj_set_x(ui_btnUnlockScreen, -10);
    lv_obj_set_y(ui_btnUnlockScreen, 2);
    lv_obj_set_align(ui_btnUnlockScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnUnlockScreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnUnlockScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnUnlockScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnUnlockScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnUnlockScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnUnlockScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_btnUnlockScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_btnUnlockScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnUnlockScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnUnlockScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnUnlockScreen, ui_event_btnUnlockScreen, LV_EVENT_ALL, NULL);

}

void ui_scrWallpaper_screen_destroy(void)
{
    if(ui_scrWallpaper) lv_obj_del(ui_scrWallpaper);

    // NULL screen variables
    ui_scrWallpaper = NULL;
    ui_Image3 = NULL;
    ui_Label3 = NULL;
    ui_btnUnlockScreen = NULL;

}
