// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCRTHEME_H
#define UI_SCRTHEME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrTheme
extern void ui_scrTheme_screen_init(void);
extern void ui_scrTheme_screen_destroy(void);
extern lv_obj_t * ui_scrTheme;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_lblHexnetTechnology4;
extern void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_lblLock3;
extern void ui_event_btnWhiteTheme(lv_event_t * e);
extern lv_obj_t * ui_btnWhiteTheme;
extern void ui_event_btnBlackTheme(lv_event_t * e);
extern lv_obj_t * ui_btnBlackTheme;
extern lv_obj_t * ui_lblSelectTheme;
extern lv_obj_t * ui_lblSettingsB;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

