// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCRSETTINGS_H
#define UI_SCRSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrSettings
extern void ui_scrSettings_screen_init(void);
extern void ui_scrSettings_screen_destroy(void);
extern lv_obj_t * ui_scrSettings;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_lblHexnetTechnology5;
extern void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_lblLock5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

