// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCRWALLPAPER_H
#define UI_SCRWALLPAPER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrWallpaper
extern void ui_scrWallpaper_screen_init(void);
extern void ui_scrWallpaper_screen_destroy(void);
extern lv_obj_t * ui_scrWallpaper;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
extern void ui_event_btnUnlockScreen(lv_event_t * e);
extern lv_obj_t * ui_btnUnlockScreen;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

