// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCRINIT_H
#define UI_SCRINIT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrInit
extern void ui_scrInit_screen_init(void);
extern void ui_scrInit_screen_destroy(void);
extern lv_obj_t * ui_scrInit;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_brInit;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

