// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void commScreen_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_scrMain
void ui_scrMain_screen_init(void);
lv_obj_t * ui_scrMain;
lv_obj_t * ui_Image2;
void ui_event_arcGrup1(lv_event_t * e);
lv_obj_t * ui_arcGrup1;
lv_obj_t * ui_lblGrup1Oran1;
lv_obj_t * ui_lblGrup1;
void ui_event_arcGrup2(lv_event_t * e);
lv_obj_t * ui_arcGrup2;
lv_obj_t * ui_lblGrup1Oran2;
lv_obj_t * ui_lblGrup2;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_lblHexnetTechnology;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_lblLock;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_pnlGrupSicaklikResim1;
lv_obj_t * ui_lblPnlGrup1SicaklikDeger1;
lv_obj_t * ui_lblPnlGrup1Sicaklik1;
lv_obj_t * ui_lblPnlGrup1Sicaklik2;
lv_obj_t * ui_lblPnlGrup1SicaklikDeger2;
lv_obj_t * ui_pnlGrupSicaklikResim2;
lv_obj_t * ui_pnlOutputs;
lv_obj_t * ui_imgBluetoothConnected;
lv_obj_t * ui_lblVangoText;
lv_obj_t * ui_imgsconnected;
lv_obj_t * ui_imgsnotconnected;
lv_obj_t * ui_imgBluetoothNotConnected;
lv_obj_t * ui_imgWForecast;
lv_obj_t * ui_lblDateAndTime;
lv_obj_t * ui_pnlSensors;
lv_obj_t * ui_lblWeather;
lv_obj_t * ui_pnlConnectionLost;
lv_obj_t * ui_Label1;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label6;
lv_obj_t * ui_btnRGBColor;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Button6;
lv_obj_t * ui_Button22;
// CUSTOM VARIABLES


// SCREEN: ui_scrPanelSettings
void ui_scrPanelSettings_screen_init(void);
lv_obj_t * ui_scrPanelSettings;
lv_obj_t * ui_Panel10;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_lblLock4;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_lblSettings2;
lv_obj_t * ui_pnlSaveConfigs;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label9;
lv_obj_t * ui_pbSaveConfigs;
// CUSTOM VARIABLES


// SCREEN: ui_scrWallpaper
void ui_scrWallpaper_screen_init(void);
lv_obj_t * ui_scrWallpaper;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label3;
void ui_event_btnUnlockScreen(lv_event_t * e);
lv_obj_t * ui_btnUnlockScreen;
// CUSTOM VARIABLES


// SCREEN: ui_scrInit
void ui_scrInit_screen_init(void);
lv_obj_t * ui_scrInit;
lv_obj_t * ui_Label8;
lv_obj_t * ui_brInit;
lv_obj_t * ui_Image15;
lv_obj_t * ui_Image16;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Image18;
lv_obj_t * ui_Image19;
lv_obj_t * ui_Image20;
lv_obj_t * ui_Image21;
lv_obj_t * ui_Image22;
lv_obj_t * ui_Image23;
lv_obj_t * ui_Image24;
lv_obj_t * ui_Image25;
lv_obj_t * ui_Label5;
// CUSTOM VARIABLES


// SCREEN: ui_scrCalibration
void ui_scrCalibration_screen_init(void);
lv_obj_t * ui_scrCalibration;
lv_obj_t * ui_Panel6;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
lv_obj_t * ui_lblLock7;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Panel1;
// CUSTOM VARIABLES


// SCREEN: ui_scrDimsandSensorsandWaters
void ui_scrDimsandSensorsandWaters_screen_init(void);
lv_obj_t * ui_scrDimsandSensorsandWaters;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_lblHexnetTechnology3;
void ui_event_Button21(lv_event_t * e);
lv_obj_t * ui_Button21;
lv_obj_t * ui_lblLock8;
lv_obj_t * ui_slDim1;
lv_obj_t * ui_slDim2;
lv_obj_t * ui_slDim3;
lv_obj_t * ui_slDim4;
lv_obj_t * ui_lblDim1;
lv_obj_t * ui_lblDim2;
lv_obj_t * ui_lblDim3;
lv_obj_t * ui_lblDim4;
lv_obj_t * ui_arcTemperature1;
lv_obj_t * ui_lblTemperature1;
lv_obj_t * ui_arcTemperature2;
lv_obj_t * ui_lblTemperature2;
lv_obj_t * ui_lblUnderArcTemperature1;
lv_obj_t * ui_lblUnderArcTemperature2;
lv_obj_t * ui_arcWater1;
lv_obj_t * ui_lblWater1;
lv_obj_t * ui_arcWater2;
lv_obj_t * ui_lblWater2;
lv_obj_t * ui_lblUnderArcWater1;
lv_obj_t * ui_lblUnderArcWater2;
lv_obj_t * ui_imgTemp1;
lv_obj_t * ui_imgTemp2;
// CUSTOM VARIABLES


// SCREEN: ui_scrSettings
void ui_scrSettings_screen_init(void);
lv_obj_t * ui_scrSettings;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_lblHexnetTechnology5;
void ui_event_Button18(lv_event_t * e);
lv_obj_t * ui_Button18;
lv_obj_t * ui_lblLock5;
// CUSTOM VARIABLES


// SCREEN: ui_scrRGB
void ui_scrRGB_screen_init(void);
lv_obj_t * ui_scrRGB;
void ui_event_swRGBTurnON(lv_event_t * e);
lv_obj_t * ui_swRGBTurnON;
lv_obj_t * ui_Colorwheel1;
void ui_event_btnRGBApply(lv_event_t * e);
lv_obj_t * ui_btnRGBApply;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_lblHexnetTechnology2;
lv_obj_t * ui_Label2;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_lblLock2;
// CUSTOM VARIABLES


// SCREEN: ui_scrTheme
void ui_scrTheme_screen_init(void);
lv_obj_t * ui_scrTheme;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_lblHexnetTechnology4;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_lblLock3;
void ui_event_btnWhiteTheme(lv_event_t * e);
lv_obj_t * ui_btnWhiteTheme;
void ui_event_btnBlackTheme(lv_event_t * e);
lv_obj_t * ui_btnBlackTheme;
lv_obj_t * ui_lblSelectTheme;
lv_obj_t * ui_lblSettingsB;
// CUSTOM VARIABLES


// SCREEN: ui_scrPages
void ui_scrPages_screen_init(void);
lv_obj_t * ui_scrPages;
void ui_event_btnDims(lv_event_t * e);
lv_obj_t * ui_btnDims;
void ui_event_btnTemperatures(lv_event_t * e);
lv_obj_t * ui_btnTemperatures;
void ui_event_btnWaters(lv_event_t * e);
lv_obj_t * ui_btnWaters;
void ui_event_btnRGBs(lv_event_t * e);
lv_obj_t * ui_btnRGBs;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_lblHexnetTechnology6;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
void ui_event_Button19(lv_event_t * e);
lv_obj_t * ui_Button19;
lv_obj_t * ui_lblLock6;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_arc[1] = {&ui_img_arc1_png};
const lv_img_dsc_t * ui_imgset_arcdesign[1] = {&ui_img_arcdesign2_png};
const lv_img_dsc_t * ui_imgset_btnsettings[1] = {&ui_img_btnsettings2_png};
const lv_img_dsc_t * ui_imgset_logo[1] = {&ui_img_logo3_png};
const lv_img_dsc_t * ui_imgset_outcontrols[1] = {&ui_img_outcontrols2_png};
const lv_img_dsc_t * ui_imgset_weatherforecast[1] = {&ui_img_weatherforecast2_png};
const lv_img_dsc_t * ui_imgset_wifi[1] = {&ui_img_wifi3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void commScreen_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 100);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 10);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 500);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 500);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 10);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_arcGrup1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        arcTemizSuValueChanged(e);
    }
}

void ui_event_arcGrup2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        arcTemizSuValueChanged(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrPages, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrPages_screen_init);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_pnlConnectionLost, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        savePanelSettings(e);
    }
}

void ui_event_btnUnlockScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_Button21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrPages, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrPages_screen_init);
        btnReturnfromscrDimsandSensorstoscrMainCallback(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrPanelSettings, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrPanelSettings_screen_init);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrTheme, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrTheme_screen_init);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrCalibration, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrCalibration_screen_init);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrCalibration, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrCalibration_screen_init);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrPages, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrPages_screen_init);
    }
}

void ui_event_swRGBTurnON(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_Colorwheel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        enRGBTurnONFunc(e);
        _ui_flag_modify(ui_btnRGBApply, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_Colorwheel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        enRGBTurnOFFFunc(e);
        _ui_flag_modify(ui_btnRGBApply, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_btnRGBApply(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        applyRGBColor(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrPages, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrPages_screen_init);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_scrMain_screen_init);
        btnSaveThemeFunc(e);
    }
}

void ui_event_btnWhiteTheme(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnThemeWhiteFunc(e);
    }
}

void ui_event_btnBlackTheme(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnBlackThemeFunc(e);
    }
}

void ui_event_btnDims(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrDimsandSensorsandWaters, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0,
                          &ui_scrDimsandSensorsandWaters_screen_init);
        btnDimsCallbackFunc(e);
    }
}

void ui_event_btnTemperatures(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrDimsandSensorsandWaters, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0,
                          &ui_scrDimsandSensorsandWaters_screen_init);
        btnTemperaturesCallbackFunc(e);
    }
}

void ui_event_btnWaters(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrDimsandSensorsandWaters, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0,
                          &ui_scrDimsandSensorsandWaters_screen_init);
        btnWatersCallbackFunc(e);
    }
}

void ui_event_btnRGBs(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrRGB, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrRGB_screen_init);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrSettings, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrSettings_screen_init);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrMain_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scrMain_screen_init();
    ui_scrPanelSettings_screen_init();
    ui_scrWallpaper_screen_init();
    ui_scrInit_screen_init();
    ui_scrCalibration_screen_init();
    ui_scrDimsandSensorsandWaters_screen_init();
    ui_scrSettings_screen_init();
    ui_scrRGB_screen_init();
    ui_scrTheme_screen_init();
    ui_scrPages_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_scrMain);
}
