// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void InitBar_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_scrMain
void ui_scrMain_screen_init(void);
extern lv_obj_t * ui_scrMain;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_pnlGrup1;
void ui_event_arcGrup1(lv_event_t * e);
extern lv_obj_t * ui_arcGrup1;
extern lv_obj_t * ui_lblGrup1;
extern lv_obj_t * ui_lblGrup1Oran1;
extern lv_obj_t * ui_pnlGrup2;
void ui_event_arcGrup2(lv_event_t * e);
extern lv_obj_t * ui_arcGrup2;
extern lv_obj_t * ui_lblGrup2;
extern lv_obj_t * ui_lblGrup1Oran2;
extern lv_obj_t * ui_pnlGrup3;
void ui_event_arcGrup3(lv_event_t * e);
extern lv_obj_t * ui_arcGrup3;
extern lv_obj_t * ui_lblGrup3;
extern lv_obj_t * ui_lblGrup1Oran3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_lblHexnetTechnology;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_lblLock;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_lblSettings;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_pnlGrupSicaklik1;
extern lv_obj_t * ui_pnlGrupSicaklikResim1;
extern lv_obj_t * ui_lblPnlGrup1Sicaklik1;
extern lv_obj_t * ui_lblPnlGrup1SicaklikDeger1;
extern lv_obj_t * ui_pnlGrupSicaklik2;
extern lv_obj_t * ui_pnlGrupSicaklikResim2;
extern lv_obj_t * ui_lblPnlGrup1Sicaklik2;
extern lv_obj_t * ui_lblPnlGrup1SicaklikDeger2;
extern lv_obj_t * ui_pnlOutputs;
extern lv_obj_t * ui_imgBluetoothConnected;
extern lv_obj_t * ui_lblVangoText;
extern lv_obj_t * ui_imgsconnected;
extern lv_obj_t * ui_imgsnotconnected;
extern lv_obj_t * ui_imgBluetoothNotConnected;
extern lv_obj_t * ui_imgWForecast;
extern lv_obj_t * ui_lblDateAndTime;
extern lv_obj_t * ui_pnlSensors;
extern lv_obj_t * ui_lblWeather;
extern lv_obj_t * ui_pnlConnectionLost;
extern lv_obj_t * ui_Label1;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label6;
void ui_event_btnRGBColor(lv_event_t * e);
extern lv_obj_t * ui_btnRGBColor;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

// SCREEN: ui_scrSettings
void ui_scrSettings_screen_init(void);
extern lv_obj_t * ui_scrSettings;
extern lv_obj_t * ui_lblSettingsB;
extern lv_obj_t * ui_Panel5;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_lblLock3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label10;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_scrPanelSettings
void ui_scrPanelSettings_screen_init(void);
extern lv_obj_t * ui_scrPanelSettings;
extern lv_obj_t * ui_lblPanelSettings;
void ui_event_swO1(lv_event_t * e);
extern lv_obj_t * ui_swO1;
extern lv_obj_t * ui_cbxO1;
extern lv_obj_t * ui_cbxO2;
void ui_event_swO2(lv_event_t * e);
extern lv_obj_t * ui_swO2;
void ui_event_swO3(lv_event_t * e);
extern lv_obj_t * ui_swO3;
extern lv_obj_t * ui_cbxO3;
void ui_event_swO4(lv_event_t * e);
extern lv_obj_t * ui_swO4;
extern lv_obj_t * ui_cbxO4;
void ui_event_swO5(lv_event_t * e);
extern lv_obj_t * ui_swO5;
extern lv_obj_t * ui_cbxO5;
void ui_event_swO6(lv_event_t * e);
extern lv_obj_t * ui_swO6;
extern lv_obj_t * ui_cbxO6;
void ui_event_swO7(lv_event_t * e);
extern lv_obj_t * ui_swO7;
extern lv_obj_t * ui_cbxO7;
void ui_event_swO8(lv_event_t * e);
extern lv_obj_t * ui_swO8;
extern lv_obj_t * ui_cbxO8;
void ui_event_swO9(lv_event_t * e);
extern lv_obj_t * ui_swO9;
extern lv_obj_t * ui_cbxO9;
extern lv_obj_t * ui_cbxO10;
void ui_event_swO10(lv_event_t * e);
extern lv_obj_t * ui_swO10;
void ui_event_swO11(lv_event_t * e);
extern lv_obj_t * ui_swO11;
extern lv_obj_t * ui_cbxO11;
void ui_event_swO12(lv_event_t * e);
extern lv_obj_t * ui_swO12;
extern lv_obj_t * ui_cbxO12;
void ui_event_swO14(lv_event_t * e);
extern lv_obj_t * ui_swO14;
extern lv_obj_t * ui_cbxO13;
extern lv_obj_t * ui_cbxO14;
void ui_event_swO15(lv_event_t * e);
extern lv_obj_t * ui_swO15;
extern lv_obj_t * ui_cbxO15;
void ui_event_swO16(lv_event_t * e);
extern lv_obj_t * ui_swO16;
extern lv_obj_t * ui_cbxO16;
void ui_event_swO13(lv_event_t * e);
extern lv_obj_t * ui_swO13;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_Checkbox2;
extern lv_obj_t * ui_Checkbox3;
extern lv_obj_t * ui_Checkbox4;
extern lv_obj_t * ui_Checkbox5;
extern lv_obj_t * ui_Checkbox6;
extern lv_obj_t * ui_Panel10;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_lblLock4;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_lblSettings2;
extern lv_obj_t * ui_lblSensors;
extern lv_obj_t * ui_lblDimmableOutputs;
void ui_event_swDim1(lv_event_t * e);
extern lv_obj_t * ui_swDim1;
extern lv_obj_t * ui_cbxDim1;
extern lv_obj_t * ui_cbxDim2;
extern lv_obj_t * ui_cbxDim3;
extern lv_obj_t * ui_cbxDim4;
void ui_event_swDim2(lv_event_t * e);
extern lv_obj_t * ui_swDim2;
void ui_event_swDim3(lv_event_t * e);
extern lv_obj_t * ui_swDim3;
void ui_event_swDim4(lv_event_t * e);
extern lv_obj_t * ui_swDim4;
// CUSTOM VARIABLES

// SCREEN: ui_scrWallpaper
void ui_scrWallpaper_screen_init(void);
extern lv_obj_t * ui_scrWallpaper;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
void ui_event_btnUnlockScreen(lv_event_t * e);
extern lv_obj_t * ui_btnUnlockScreen;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image13;
// CUSTOM VARIABLES

// SCREEN: ui_scrTheme
void ui_scrTheme_screen_init(void);
extern lv_obj_t * ui_scrTheme;
void ui_event_btnWhiteTheme(lv_event_t * e);
extern lv_obj_t * ui_btnWhiteTheme;
extern lv_obj_t * ui_lblSelectTheme;
void ui_event_btnBlackTheme(lv_event_t * e);
extern lv_obj_t * ui_btnBlackTheme;
extern lv_obj_t * ui_Panel4;
void ui_event_btnSaveTheme(lv_event_t * e);
extern lv_obj_t * ui_btnSaveTheme;
extern lv_obj_t * ui_lblLock2;
extern lv_obj_t * ui_lblWallpaper;
void ui_event_swEnableWallpaper(lv_event_t * e);
extern lv_obj_t * ui_swEnableWallpaper;
extern lv_obj_t * ui_rlrTime;
extern lv_obj_t * ui_lblRolllerTime;
// CUSTOM VARIABLES

// SCREEN: ui_scrRules
void ui_scrRules_screen_init(void);
extern lv_obj_t * ui_scrRules;
extern lv_obj_t * ui_Panel12;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_lblLock5;
extern lv_obj_t * ui_lblRuleList;
extern lv_obj_t * ui_TextArea2;
// CUSTOM VARIABLES

// SCREEN: ui_scrRGB
void ui_scrRGB_screen_init(void);
extern lv_obj_t * ui_scrRGB;
extern lv_obj_t * ui_Panel3;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_lblLock6;
void ui_event_Colorwheel1(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel1;
void ui_event_btnRGBApply(lv_event_t * e);
extern lv_obj_t * ui_btnRGBApply;
extern lv_obj_t * ui_Label5;
void ui_event_swRGBTurnON(lv_event_t * e);
extern lv_obj_t * ui_swRGBTurnON;
// CUSTOM VARIABLES

// SCREEN: ui_scrInit
void ui_scrInit_screen_init(void);
extern lv_obj_t * ui_scrInit;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_brInit;
// CUSTOM VARIABLES

// SCREEN: ui_scrConnectionSettings
void ui_scrConnectionSettings_screen_init(void);
extern lv_obj_t * ui_scrConnectionSettings;
extern lv_obj_t * ui_Panel6;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_lblLock7;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo3_png);    // assets/logo3.png
LV_IMG_DECLARE(ui_img_1542361832);    // assets/New Project (1).png
LV_IMG_DECLARE(ui_img_btconnected_png);    // assets/btconnected.png
LV_IMG_DECLARE(ui_img_sconnected_png);    // assets/sconnected.png
LV_IMG_DECLARE(ui_img_snotconnected_png);    // assets/snotconnected.png
LV_IMG_DECLARE(ui_img_btnotconnected_png);    // assets/btnotconnected.png
LV_IMG_DECLARE(ui_img_weatherforecast2_png);    // assets/weatherforecast2.png
LV_IMG_DECLARE(ui_img_connectionimg_png);    // assets/connectionimg.png
LV_IMG_DECLARE(ui_img_themeimg_png);    // assets/themeimg.png
LV_IMG_DECLARE(ui_img_panelsettingimg_png);    // assets/panelsettingimg.png
LV_IMG_DECLARE(ui_img_caravan_logo_png);    // assets/caravan logo.png
LV_IMG_DECLARE(ui_img_ac_png);    // assets/AC.png
LV_IMG_DECLARE(ui_img_heater_png);    // assets/heater.png
LV_IMG_DECLARE(ui_img_lamp_png);    // assets/lamp.png
LV_IMG_DECLARE(ui_img_outlet_png);    // assets/outlet.png
LV_IMG_DECLARE(ui_img_oven_png);    // assets/oven.png
LV_IMG_DECLARE(ui_img_readinglamp_png);    // assets/readinglamp.png
LV_IMG_DECLARE(ui_img_refrigerator_png);    // assets/refrigerator.png
LV_IMG_DECLARE(ui_img_toilet_png);    // assets/toilet.png
LV_IMG_DECLARE(ui_img_tv_png);    // assets/tv.png
LV_IMG_DECLARE(ui_img_usb_png);    // assets/usb.png
LV_IMG_DECLARE(ui_img_water_png);    // assets/water.png
LV_IMG_DECLARE(ui_img_initlogo_png);    // assets/initlogo.png
LV_IMG_DECLARE(ui_img_wifi3_png);    // assets/wifi3.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
