// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void commScreen_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_scrMain
void ui_scrMain_screen_init(void);
extern lv_obj_t * ui_scrMain;
extern lv_obj_t * ui_Image2;
void ui_event_arcGrup1(lv_event_t * e);
extern lv_obj_t * ui_arcGrup1;
extern lv_obj_t * ui_lblGrup1Oran1;
extern lv_obj_t * ui_lblGrup1;
void ui_event_arcGrup2(lv_event_t * e);
extern lv_obj_t * ui_arcGrup2;
extern lv_obj_t * ui_lblGrup1Oran2;
extern lv_obj_t * ui_lblGrup2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_lblHexnetTechnology;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_lblLock;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_pnlGrupSicaklikResim1;
extern lv_obj_t * ui_lblPnlGrup1SicaklikDeger1;
extern lv_obj_t * ui_lblPnlGrup1Sicaklik1;
extern lv_obj_t * ui_lblPnlGrup1Sicaklik2;
extern lv_obj_t * ui_lblPnlGrup1SicaklikDeger2;
extern lv_obj_t * ui_pnlGrupSicaklikResim2;
extern lv_obj_t * ui_pnlOutputs;
extern lv_obj_t * ui_imgBluetoothConnected;
extern lv_obj_t * ui_lblVangoText;
extern lv_obj_t * ui_imgsconnected;
extern lv_obj_t * ui_imgsnotconnected;
extern lv_obj_t * ui_imgBluetoothNotConnected;
extern lv_obj_t * ui_imgWForecast;
extern lv_obj_t * ui_lblDateAndTime;
extern lv_obj_t * ui_pnlSensors;
extern lv_obj_t * ui_lblWeather;
extern lv_obj_t * ui_pnlConnectionLost;
extern lv_obj_t * ui_Label1;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_btnRGBColor;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button22;
// CUSTOM VARIABLES

// SCREEN: ui_scrPanelSettings
void ui_scrPanelSettings_screen_init(void);
extern lv_obj_t * ui_scrPanelSettings;
extern lv_obj_t * ui_Panel10;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_lblLock4;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_lblSettings2;
extern lv_obj_t * ui_pnlSaveConfigs;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_pbSaveConfigs;
// CUSTOM VARIABLES

// SCREEN: ui_scrWallpaper
void ui_scrWallpaper_screen_init(void);
extern lv_obj_t * ui_scrWallpaper;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
void ui_event_btnUnlockScreen(lv_event_t * e);
extern lv_obj_t * ui_btnUnlockScreen;
// CUSTOM VARIABLES

// SCREEN: ui_scrInit
void ui_scrInit_screen_init(void);
extern lv_obj_t * ui_scrInit;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_brInit;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

// SCREEN: ui_scrCalibration
void ui_scrCalibration_screen_init(void);
extern lv_obj_t * ui_scrCalibration;
extern lv_obj_t * ui_Panel6;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_lblLock7;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel1;
// CUSTOM VARIABLES

// SCREEN: ui_scrDimsandSensorsandWaters
void ui_scrDimsandSensorsandWaters_screen_init(void);
extern lv_obj_t * ui_scrDimsandSensorsandWaters;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_lblHexnetTechnology3;
void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_lblLock8;
extern lv_obj_t * ui_slDim1;
extern lv_obj_t * ui_slDim2;
extern lv_obj_t * ui_slDim3;
extern lv_obj_t * ui_slDim4;
extern lv_obj_t * ui_lblDim1;
extern lv_obj_t * ui_lblDim2;
extern lv_obj_t * ui_lblDim3;
extern lv_obj_t * ui_lblDim4;
extern lv_obj_t * ui_arcTemperature1;
extern lv_obj_t * ui_lblTemperature1;
extern lv_obj_t * ui_arcTemperature2;
extern lv_obj_t * ui_lblTemperature2;
extern lv_obj_t * ui_lblUnderArcTemperature1;
extern lv_obj_t * ui_lblUnderArcTemperature2;
extern lv_obj_t * ui_arcWater1;
extern lv_obj_t * ui_lblWater1;
extern lv_obj_t * ui_arcWater2;
extern lv_obj_t * ui_lblWater2;
extern lv_obj_t * ui_lblUnderArcWater1;
extern lv_obj_t * ui_lblUnderArcWater2;
extern lv_obj_t * ui_imgTemp1;
extern lv_obj_t * ui_imgTemp2;
// CUSTOM VARIABLES

// SCREEN: ui_scrSettings
void ui_scrSettings_screen_init(void);
extern lv_obj_t * ui_scrSettings;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_lblHexnetTechnology5;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_lblLock5;
// CUSTOM VARIABLES

// SCREEN: ui_scrRGB
void ui_scrRGB_screen_init(void);
extern lv_obj_t * ui_scrRGB;
void ui_event_swRGBTurnON(lv_event_t * e);
extern lv_obj_t * ui_swRGBTurnON;
extern lv_obj_t * ui_Colorwheel1;
void ui_event_btnRGBApply(lv_event_t * e);
extern lv_obj_t * ui_btnRGBApply;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_lblHexnetTechnology2;
extern lv_obj_t * ui_Label2;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_lblLock2;
// CUSTOM VARIABLES

// SCREEN: ui_scrTheme
void ui_scrTheme_screen_init(void);
extern lv_obj_t * ui_scrTheme;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_lblHexnetTechnology4;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_lblLock3;
void ui_event_btnWhiteTheme(lv_event_t * e);
extern lv_obj_t * ui_btnWhiteTheme;
void ui_event_btnBlackTheme(lv_event_t * e);
extern lv_obj_t * ui_btnBlackTheme;
extern lv_obj_t * ui_lblSelectTheme;
extern lv_obj_t * ui_lblSettingsB;
// CUSTOM VARIABLES

// SCREEN: ui_scrPages
void ui_scrPages_screen_init(void);
extern lv_obj_t * ui_scrPages;
void ui_event_btnDims(lv_event_t * e);
extern lv_obj_t * ui_btnDims;
void ui_event_btnTemperatures(lv_event_t * e);
extern lv_obj_t * ui_btnTemperatures;
void ui_event_btnWaters(lv_event_t * e);
extern lv_obj_t * ui_btnWaters;
void ui_event_btnRGBs(lv_event_t * e);
extern lv_obj_t * ui_btnRGBs;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_lblHexnetTechnology6;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_lblLock6;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo3_png);    // assets/logo3.png
LV_IMG_DECLARE(ui_img_1542361832);    // assets/New Project (1).png
LV_IMG_DECLARE(ui_img_btconnected_png);    // assets/btconnected.png
LV_IMG_DECLARE(ui_img_sconnected_png);    // assets/sconnected.png
LV_IMG_DECLARE(ui_img_snotconnected_png);    // assets/snotconnected.png
LV_IMG_DECLARE(ui_img_btnotconnected_png);    // assets/btnotconnected.png
LV_IMG_DECLARE(ui_img_weatherforecast2_png);    // assets/weatherforecast2.png
LV_IMG_DECLARE(ui_img_button_up_png);    // assets/button up.png
LV_IMG_DECLARE(ui_img_button_down_png);    // assets/button down.png
LV_IMG_DECLARE(ui_img_caravan_logo_png);    // assets/caravan logo.png
LV_IMG_DECLARE(ui_img_ac_png);    // assets/AC.png
LV_IMG_DECLARE(ui_img_heater_png);    // assets/heater.png
LV_IMG_DECLARE(ui_img_lamp_png);    // assets/lamp.png
LV_IMG_DECLARE(ui_img_outlet_png);    // assets/outlet.png
LV_IMG_DECLARE(ui_img_oven_png);    // assets/oven.png
LV_IMG_DECLARE(ui_img_readinglamp_png);    // assets/readinglamp.png
LV_IMG_DECLARE(ui_img_refrigerator_png);    // assets/refrigerator.png
LV_IMG_DECLARE(ui_img_toilet_png);    // assets/toilet.png
LV_IMG_DECLARE(ui_img_tv_png);    // assets/tv.png
LV_IMG_DECLARE(ui_img_usb_png);    // assets/usb.png
LV_IMG_DECLARE(ui_img_water_png);    // assets/water.png
LV_IMG_DECLARE(ui_img_1096609443);    // assets/connstatusıcons.png
LV_IMG_DECLARE(ui_img_sliderpassive_png);    // assets/sliderpassive.png
LV_IMG_DECLARE(ui_img_slideractivee_png);    // assets/slideractivee.png
LV_IMG_DECLARE(ui_img_arcdesign2_png);    // assets/arcdesign2.png
LV_IMG_DECLARE(ui_img_arcdesign_png);    // assets/arcdesign.png
LV_IMG_DECLARE(ui_img_tempicon_png);    // assets/tempicon.png
LV_IMG_DECLARE(ui_img_outcontrols_png);    // assets/outcontrols.png
LV_IMG_DECLARE(ui_img_theme_png);    // assets/theme.png
LV_IMG_DECLARE(ui_img_connectioncontrol_png);    // assets/connectioncontrol.png
LV_IMG_DECLARE(ui_img_calibration_png);    // assets/calibration.png
LV_IMG_DECLARE(ui_img_btnsettings2_png);    // assets/btnSettings2.png
LV_IMG_DECLARE(ui_img_sensors_png);    // assets/sensors.png
LV_IMG_DECLARE(ui_img_waterlevel_png);    // assets/waterlevel.png
LV_IMG_DECLARE(ui_img_rgbcontrol_png);    // assets/rgbcontrol.png
LV_IMG_DECLARE(ui_img_settingsicon_png);    // assets/settingsicon.png
LV_IMG_DECLARE(ui_img_arc1_png);    // assets/arc1.png
LV_IMG_DECLARE(ui_img_outcontrols2_png);    // assets/outcontrols2.png
LV_IMG_DECLARE(ui_img_wifi3_png);    // assets/wifi3.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
