// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "display_manager.h"
#include "definitions.h"

void slMutfakValueChanged(lv_event_t * e)
{
	// Your code here
}

void arcTemizSuValueChanged(lv_event_t * e)
{
	// Your code here
}

void turnThemeWhite(lv_event_t * e)
{
	// Your code here
}

void btnThemeWhiteFunc(lv_event_t * e)
{
	my_btnThemeWhiteFunc();
}

void btnBlackThemeFunc(lv_event_t * e)
{
	my_btnBlackThemeFunc();
}

void denemezartzurt(lv_event_t * e)
{
	// Your code here
}

void savePanelSettings(lv_event_t * e)
{
	save_panel_settings();
}

void btnSaveThemeFunc(lv_event_t * e)
{
	save_theme_settings();
}


void changeColorWheel(lv_event_t * e)
{
	
}

void applyRGBColor(lv_event_t * e)
{
	color_wheel_event_cb();
}

void enRGBSetWhiteFunc(lv_event_t * e)
{

}

void enRGBTurnONFunc(lv_event_t * e)
{
	set_RGBTurnONOFF(1);
	set_rgb_to_white();
}

void enRGBTurnOFFFunc(lv_event_t * e)
{
	set_RGBTurnONOFF(0);
	set_rgb_to_white();
}

void btnDimsCallbackFunc(lv_event_t * e)
{
	// Hide temperature widgets
	lv_obj_add_flag(ui_arcTemperature1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblTemperature1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_arcTemperature2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblTemperature2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblUnderArcTemperature1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblUnderArcTemperature2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_imgTemp1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_imgTemp2, LV_OBJ_FLAG_HIDDEN);
	
	// Hide water widgets
	lv_obj_add_flag(ui_arcWater1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblWater1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_arcWater2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblWater2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblUnderArcWater1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblUnderArcWater2, LV_OBJ_FLAG_HIDDEN);
	
	// Show dim widgets
	lv_obj_clear_flag(ui_slDim1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_slDim2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_slDim3, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_slDim4, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_lblDim1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_lblDim2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_lblDim3, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_lblDim4, LV_OBJ_FLAG_HIDDEN);
}

void btnTemperaturesCallbackFunc(lv_event_t * e)
{
	// Hide dim widgets
	lv_obj_add_flag(ui_slDim1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_slDim2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_slDim3, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_slDim4, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblDim1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblDim2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblDim3, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblDim4, LV_OBJ_FLAG_HIDDEN);
	
	// Show temperature widgets
	lv_obj_clear_flag(ui_lblTemperature1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_lblTemperature2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_lblUnderArcTemperature1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_lblUnderArcTemperature2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_imgTemp1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_imgTemp2, LV_OBJ_FLAG_HIDDEN);
	
	// Hide water widgets
	lv_obj_add_flag(ui_arcWater1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblWater1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_arcWater2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblWater2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblUnderArcWater1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblUnderArcWater2, LV_OBJ_FLAG_HIDDEN);
}

void btnWatersCallbackFunc(lv_event_t * e)
{
	// Hide dim widgets
	lv_obj_add_flag(ui_slDim1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_slDim2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_slDim3, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_slDim4, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblDim1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblDim2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblDim3, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblDim4, LV_OBJ_FLAG_HIDDEN);
	
	// Hide temperature widgets
	lv_obj_add_flag(ui_arcTemperature1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblTemperature1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_arcTemperature2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblTemperature2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblUnderArcTemperature1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_lblUnderArcTemperature2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_imgTemp1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_imgTemp2, LV_OBJ_FLAG_HIDDEN);
	
	// Show water widgets
	lv_obj_clear_flag(ui_arcWater1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_lblWater1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_arcWater2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_lblWater2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_lblUnderArcWater1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_lblUnderArcWater2, LV_OBJ_FLAG_HIDDEN);
}

void btnReturnfromscrDimsandSensorstoscrMainCallback(lv_event_t * e)
{
	// This function is called when returning from the dims/sensors screen
	// Currently empty, but can be used for cleanup or state management
}

