// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void arcTemizSuValueChanged(lv_event_t * e);
void savePanelSettings(lv_event_t * e);
void btnThemeWhiteFunc(lv_event_t * e);
void btnBlackThemeFunc(lv_event_t * e);
void btnSaveThemeFunc(lv_event_t * e);
void changeColorWheel(lv_event_t * e);
void applyRGBColor(lv_event_t * e);
void enRGBSetWhiteFunc(lv_event_t * e);
void enRGBTurnONFunc(lv_event_t * e);
void enRGBTurnOFFFunc(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
