// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_scrDimsandSensorsandWaters_screen_init(void)
{
    ui_scrDimsandSensorsandWaters = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrDimsandSensorsandWaters, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrDimsandSensorsandWaters, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrDimsandSensorsandWaters, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_Panel8, 797);
    lv_obj_set_height(ui_Panel8, 42);
    lv_obj_set_x(ui_Panel8, 0);
    lv_obj_set_y(ui_Panel8, 215);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x006592), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHexnetTechnology3 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_lblHexnetTechnology3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHexnetTechnology3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHexnetTechnology3, 13);
    lv_obj_set_y(ui_lblHexnetTechnology3, 0);
    lv_obj_set_align(ui_lblHexnetTechnology3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHexnetTechnology3, "HEXNET TECHNOLOGY");
    lv_obj_set_style_text_color(ui_lblHexnetTechnology3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHexnetTechnology3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblHexnetTechnology3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button21 = lv_btn_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_Button21, 136);
    lv_obj_set_height(ui_Button21, 98);
    lv_obj_set_x(ui_Button21, -333);
    lv_obj_set_y(ui_Button21, 193);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button21, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button21, lv_color_hex(0x00AAF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button21, lv_color_hex(0x00B0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button21, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button21, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblLock8 = lv_label_create(ui_Button21);
    lv_obj_set_width(ui_lblLock8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblLock8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblLock8, 1);
    lv_obj_set_y(ui_lblLock8, 0);
    lv_obj_set_align(ui_lblLock8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLock8, "Return");
    lv_obj_set_style_text_color(ui_lblLock8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblLock8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblLock8, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slDim1 = lv_slider_create(ui_scrDimsandSensorsandWaters);
    lv_slider_set_value(ui_slDim1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_slDim1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_slDim1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_slDim1, 522);
    lv_obj_set_height(ui_slDim1, 86);
    lv_obj_set_x(ui_slDim1, 69);
    lv_obj_set_y(ui_slDim1, -182);
    lv_obj_set_align(ui_slDim1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_slDim1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_slDim1, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slDim1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slDim1, &ui_img_sliderpassive_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_slDim1, lv_color_hex(0xF6EFEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_slDim1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_slDim1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_slDim1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_slDim1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_slDim1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_slDim1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_slDim1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slDim1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slDim1, &ui_img_slideractivee_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_slDim1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_slDim1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_slDim1, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_slDim1, lv_color_hex(0x2095F6), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_slDim1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_slDim1, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_slDim1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_slDim2 = lv_slider_create(ui_scrDimsandSensorsandWaters);
    lv_slider_set_value(ui_slDim2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_slDim2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_slDim2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_slDim2, 522);
    lv_obj_set_height(ui_slDim2, 86);
    lv_obj_set_x(ui_slDim2, 72);
    lv_obj_set_y(ui_slDim2, -79);
    lv_obj_set_align(ui_slDim2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_slDim2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_slDim2, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slDim2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slDim2, &ui_img_sliderpassive_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_slDim2, lv_color_hex(0xF6EFEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_slDim2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_slDim2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_slDim2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_slDim2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_slDim2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_slDim2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_slDim2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slDim2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slDim2, &ui_img_slideractivee_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_slDim2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_slDim2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_slDim2, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_slDim2, lv_color_hex(0x2095F6), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_slDim2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_slDim2, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_slDim2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_slDim3 = lv_slider_create(ui_scrDimsandSensorsandWaters);
    lv_slider_set_value(ui_slDim3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_slDim3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_slDim3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_slDim3, 522);
    lv_obj_set_height(ui_slDim3, 86);
    lv_obj_set_x(ui_slDim3, 70);
    lv_obj_set_y(ui_slDim3, 24);
    lv_obj_set_align(ui_slDim3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_slDim3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_slDim3, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slDim3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slDim3, &ui_img_sliderpassive_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_slDim3, lv_color_hex(0xF6EFEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_slDim3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_slDim3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_slDim3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_slDim3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_slDim3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_slDim3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_slDim3, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slDim3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slDim3, &ui_img_slideractivee_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_slDim3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_slDim3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_slDim3, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_slDim3, lv_color_hex(0x2095F6), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_slDim3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_slDim3, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_slDim3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_slDim4 = lv_slider_create(ui_scrDimsandSensorsandWaters);
    lv_slider_set_value(ui_slDim4, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_slDim4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_slDim4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_slDim4, 522);
    lv_obj_set_height(ui_slDim4, 86);
    lv_obj_set_x(ui_slDim4, 69);
    lv_obj_set_y(ui_slDim4, 127);
    lv_obj_set_align(ui_slDim4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_slDim4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_slDim4, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slDim4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slDim4, &ui_img_sliderpassive_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_slDim4, lv_color_hex(0xF6EFEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_slDim4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_slDim4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_slDim4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_slDim4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_slDim4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_slDim4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_slDim4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slDim4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slDim4, &ui_img_slideractivee_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_slDim4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_slDim4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_slDim4, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_slDim4, lv_color_hex(0x2095F6), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_slDim4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_slDim4, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_slDim4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblDim1 = lv_label_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_lblDim1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDim1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDim1, -324);
    lv_obj_set_y(ui_lblDim1, -180);
    lv_obj_set_align(ui_lblDim1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDim1, "Kitchen:");
    lv_obj_add_flag(ui_lblDim1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lblDim1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDim2 = lv_label_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_lblDim2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDim2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDim2, -325);
    lv_obj_set_y(ui_lblDim2, -74);
    lv_obj_set_align(ui_lblDim2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDim2, "Kitchen:");
    lv_obj_add_flag(ui_lblDim2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lblDim2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDim3 = lv_label_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_lblDim3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDim3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDim3, -324);
    lv_obj_set_y(ui_lblDim3, 29);
    lv_obj_set_align(ui_lblDim3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDim3, "Kitchen:");
    lv_obj_add_flag(ui_lblDim3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lblDim3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDim4 = lv_label_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_lblDim4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDim4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDim4, -321);
    lv_obj_set_y(ui_lblDim4, 134);
    lv_obj_set_align(ui_lblDim4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDim4, "Kitchen:");
    lv_obj_add_flag(ui_lblDim4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lblDim4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcTemperature1 = lv_arc_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_arcTemperature1, 309);
    lv_obj_set_height(ui_arcTemperature1, 307);
    lv_obj_set_x(ui_arcTemperature1, -179);
    lv_obj_set_y(ui_arcTemperature1, -65);
    lv_obj_set_align(ui_arcTemperature1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arcTemperature1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_arcTemperature1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_arcTemperature1, 100);
    lv_arc_set_bg_angles(ui_arcTemperature1, 115, 100);
    lv_obj_set_style_radius(ui_arcTemperature1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_arcTemperature1, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_arcTemperature1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_arcTemperature1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_arcTemperature1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcTemperature1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcTemperature1, lv_color_hex(0x00FF5D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcTemperature1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcTemperature1, 60, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_arcTemperature1, &ui_img_arcdesign2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcTemperature1, lv_color_hex(0xA0FF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcTemperature1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_arcTemperature1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_arcTemperature1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_arcTemperature1, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_arcTemperature1, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arcTemperature1, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arcTemperature1, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arcTemperature1, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblTemperature1 = lv_label_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_lblTemperature1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTemperature1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTemperature1, -180);
    lv_obj_set_y(ui_lblTemperature1, -68);
    lv_obj_set_align(ui_lblTemperature1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTemperature1, "26 °C");
    lv_obj_add_flag(ui_lblTemperature1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lblTemperature1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcTemperature2 = lv_arc_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_arcTemperature2, 309);
    lv_obj_set_height(ui_arcTemperature2, 307);
    lv_obj_set_x(ui_arcTemperature2, 200);
    lv_obj_set_y(ui_arcTemperature2, -61);
    lv_obj_set_align(ui_arcTemperature2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arcTemperature2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_arcTemperature2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_arcTemperature2, 100);
    lv_arc_set_bg_angles(ui_arcTemperature2, 115, 100);
    lv_obj_set_style_radius(ui_arcTemperature2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_arcTemperature2, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_arcTemperature2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_arcTemperature2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_arcTemperature2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcTemperature2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcTemperature2, lv_color_hex(0x00FF5D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcTemperature2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcTemperature2, 60, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_arcTemperature2, &ui_img_arcdesign2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcTemperature2, lv_color_hex(0xA0FF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcTemperature2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_arcTemperature2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_arcTemperature2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_arcTemperature2, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_arcTemperature2, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arcTemperature2, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arcTemperature2, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arcTemperature2, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblTemperature2 = lv_label_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_lblTemperature2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTemperature2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTemperature2, 200);
    lv_obj_set_y(ui_lblTemperature2, -69);
    lv_obj_set_align(ui_lblTemperature2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTemperature2, "36 °C");
    lv_obj_add_flag(ui_lblTemperature2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lblTemperature2, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblUnderArcTemperature1 = lv_label_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_lblUnderArcTemperature1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblUnderArcTemperature1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblUnderArcTemperature1, -255);
    lv_obj_set_y(ui_lblUnderArcTemperature1, 114);
    lv_obj_set_align(ui_lblUnderArcTemperature1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblUnderArcTemperature1, "Internal Temperature");
    lv_obj_add_flag(ui_lblUnderArcTemperature1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lblUnderArcTemperature1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblUnderArcTemperature2 = lv_label_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_lblUnderArcTemperature2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblUnderArcTemperature2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblUnderArcTemperature2, 113);
    lv_obj_set_y(ui_lblUnderArcTemperature2, 113);
    lv_obj_set_align(ui_lblUnderArcTemperature2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblUnderArcTemperature2, "External Temperature");
    lv_obj_add_flag(ui_lblUnderArcTemperature2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lblUnderArcTemperature2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcWater1 = lv_arc_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_arcWater1, 309);
    lv_obj_set_height(ui_arcWater1, 307);
    lv_obj_set_x(ui_arcWater1, -178);
    lv_obj_set_y(ui_arcWater1, -65);
    lv_obj_set_align(ui_arcWater1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arcWater1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_arcWater1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_arcWater1, 100);
    lv_arc_set_bg_angles(ui_arcWater1, 115, 100);
    lv_obj_set_style_radius(ui_arcWater1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_arcWater1, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_arcWater1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_arcWater1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_arcWater1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcWater1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcWater1, lv_color_hex(0x00FF5D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcWater1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcWater1, 60, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_arcWater1, &ui_img_arcdesign_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcWater1, lv_color_hex(0x006594), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcWater1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_arcWater1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_arcWater1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_arcWater1, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_arcWater1, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arcWater1, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arcWater1, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arcWater1, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblWater1 = lv_label_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_lblWater1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWater1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWater1, -180);
    lv_obj_set_y(ui_lblWater1, -72);
    lv_obj_set_align(ui_lblWater1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWater1, "%29");
    lv_obj_add_flag(ui_lblWater1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lblWater1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcWater2 = lv_arc_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_arcWater2, 309);
    lv_obj_set_height(ui_arcWater2, 307);
    lv_obj_set_x(ui_arcWater2, 199);
    lv_obj_set_y(ui_arcWater2, -61);
    lv_obj_set_align(ui_arcWater2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arcWater2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_arcWater2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_arcWater2, 100);
    lv_arc_set_bg_angles(ui_arcWater2, 115, 100);
    lv_obj_set_style_radius(ui_arcWater2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_arcWater2, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_arcWater2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_arcWater2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_arcWater2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcWater2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcWater2, lv_color_hex(0x00FF5D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcWater2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcWater2, 60, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_arcWater2, &ui_img_arcdesign_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcWater2, lv_color_hex(0x006594), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcWater2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_arcWater2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_arcWater2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_arcWater2, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_arcWater2, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arcWater2, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arcWater2, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arcWater2, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblWater2 = lv_label_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_lblWater2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWater2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWater2, 204);
    lv_obj_set_y(ui_lblWater2, -70);
    lv_obj_set_align(ui_lblWater2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWater2, "%75");
    lv_obj_add_flag(ui_lblWater2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lblWater2, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblUnderArcWater1 = lv_label_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_lblUnderArcWater1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblUnderArcWater1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblUnderArcWater1, -193);
    lv_obj_set_y(ui_lblUnderArcWater1, 121);
    lv_obj_set_align(ui_lblUnderArcWater1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblUnderArcWater1, "Clean Water");
    lv_obj_add_flag(ui_lblUnderArcWater1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lblUnderArcWater1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblUnderArcWater2 = lv_label_create(ui_scrDimsandSensorsandWaters);
    lv_obj_set_width(ui_lblUnderArcWater2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblUnderArcWater2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblUnderArcWater2, 183);
    lv_obj_set_y(ui_lblUnderArcWater2, 128);
    lv_obj_set_align(ui_lblUnderArcWater2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblUnderArcWater2, "Dirty Water");
    lv_obj_add_flag(ui_lblUnderArcWater2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lblUnderArcWater2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTemp1 = lv_img_create(ui_scrDimsandSensorsandWaters);
    lv_img_set_src(ui_imgTemp1, &ui_img_tempicon_png);
    lv_obj_set_width(ui_imgTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgTemp1, -287);
    lv_obj_set_y(ui_imgTemp1, -56);
    lv_obj_set_align(ui_imgTemp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTemp1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgTemp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgTemp2 = lv_img_create(ui_scrDimsandSensorsandWaters);
    lv_img_set_src(ui_imgTemp2, &ui_img_tempicon_png);
    lv_obj_set_width(ui_imgTemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgTemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgTemp2, 96);
    lv_obj_set_y(ui_imgTemp2, -59);
    lv_obj_set_align(ui_imgTemp2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTemp2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgTemp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button21, ui_event_Button21, LV_EVENT_ALL, NULL);

}
