// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCRRGB_H
#define UI_SCRRGB_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrRGB
extern void ui_scrRGB_screen_init(void);
extern void ui_scrRGB_screen_destroy(void);
extern lv_obj_t * ui_scrRGB;
extern void ui_event_swRGBTurnON(lv_event_t * e);
extern lv_obj_t * ui_swRGBTurnON;
extern lv_obj_t * ui_Colorwheel1;
extern void ui_event_btnRGBApply(lv_event_t * e);
extern lv_obj_t * ui_btnRGBApply;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_lblHexnetTechnology2;
extern lv_obj_t * ui_Label2;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_lblLock2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

