// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_scrTheme_screen_init(void)
{
    ui_scrTheme = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrTheme, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_scrTheme);
    lv_obj_set_width(ui_Panel4, 797);
    lv_obj_set_height(ui_Panel4, 42);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, 215);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x006592), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHexnetTechnology4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_lblHexnetTechnology4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHexnetTechnology4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHexnetTechnology4, 13);
    lv_obj_set_y(ui_lblHexnetTechnology4, 0);
    lv_obj_set_align(ui_lblHexnetTechnology4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHexnetTechnology4, "HEXNET TECHNOLOGY");
    lv_obj_set_style_text_color(ui_lblHexnetTechnology4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHexnetTechnology4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblHexnetTechnology4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button14 = lv_btn_create(ui_scrTheme);
    lv_obj_set_width(ui_Button14, 136);
    lv_obj_set_height(ui_Button14, 103);
    lv_obj_set_x(ui_Button14, -336);
    lv_obj_set_y(ui_Button14, 189);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0x00AAF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button14, lv_color_hex(0x00B0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button14, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblLock3 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_lblLock3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblLock3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblLock3, 1);
    lv_obj_set_y(ui_lblLock3, 0);
    lv_obj_set_align(ui_lblLock3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLock3, "Save");
    lv_obj_set_style_text_color(ui_lblLock3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblLock3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblLock3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWhiteTheme = lv_btn_create(ui_scrTheme);
    lv_obj_set_width(ui_btnWhiteTheme, 200);
    lv_obj_set_height(ui_btnWhiteTheme, 198);
    lv_obj_set_x(ui_btnWhiteTheme, -89);
    lv_obj_set_y(ui_btnWhiteTheme, -118);
    lv_obj_set_align(ui_btnWhiteTheme, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnWhiteTheme, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnWhiteTheme, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnWhiteTheme, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnWhiteTheme, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWhiteTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnWhiteTheme, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnWhiteTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnWhiteTheme, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBlackTheme = lv_btn_create(ui_scrTheme);
    lv_obj_set_width(ui_btnBlackTheme, 209);
    lv_obj_set_height(ui_btnBlackTheme, 210);
    lv_obj_set_x(ui_btnBlackTheme, 166);
    lv_obj_set_y(ui_btnBlackTheme, -117);
    lv_obj_set_align(ui_btnBlackTheme, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBlackTheme, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBlackTheme, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnBlackTheme, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnBlackTheme, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBlackTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnBlackTheme, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnBlackTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnBlackTheme, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSelectTheme = lv_label_create(ui_scrTheme);
    lv_obj_set_width(ui_lblSelectTheme, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSelectTheme, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSelectTheme, -282);
    lv_obj_set_y(ui_lblSelectTheme, -115);
    lv_obj_set_align(ui_lblSelectTheme, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSelectTheme, "Select Theme:");
    lv_obj_set_style_text_font(ui_lblSelectTheme, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSettingsB = lv_label_create(ui_scrTheme);
    lv_obj_set_width(ui_lblSettingsB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSettingsB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSettingsB, -1778);
    lv_obj_set_y(ui_lblSettingsB, -185);
    lv_obj_set_align(ui_lblSettingsB, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWhiteTheme, ui_event_btnWhiteTheme, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnBlackTheme, ui_event_btnBlackTheme, LV_EVENT_ALL, NULL);

}
