// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCRCALIBRATION_H
#define UI_SCRCALIBRATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrCalibration
extern void ui_scrCalibration_screen_init(void);
extern void ui_scrCalibration_screen_destroy(void);
extern lv_obj_t * ui_scrCalibration;
extern lv_obj_t * ui_Panel6;
extern void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_lblLock7;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

