// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_scrTheme_screen_init(void)
{
    ui_scrTheme = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrTheme, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrTheme, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWhiteTheme = lv_btn_create(ui_scrTheme);
    lv_obj_set_width(ui_btnWhiteTheme, 336);
    lv_obj_set_height(ui_btnWhiteTheme, 211);
    lv_obj_set_x(ui_btnWhiteTheme, -213);
    lv_obj_set_y(ui_btnWhiteTheme, -89);
    lv_obj_set_align(ui_btnWhiteTheme, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnWhiteTheme, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnWhiteTheme, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnWhiteTheme, lv_color_hex(0xD7D7D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWhiteTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnWhiteTheme, &ui_img_logo3_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnWhiteTheme, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnWhiteTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnWhiteTheme, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSelectTheme = lv_label_create(ui_scrTheme);
    lv_obj_set_width(ui_lblSelectTheme, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSelectTheme, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSelectTheme, -15);
    lv_obj_set_y(ui_lblSelectTheme, -216);
    lv_obj_set_align(ui_lblSelectTheme, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSelectTheme, "SELECT THEME");
    lv_obj_set_style_text_font(ui_lblSelectTheme, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBlackTheme = lv_btn_create(ui_scrTheme);
    lv_obj_set_width(ui_btnBlackTheme, 336);
    lv_obj_set_height(ui_btnBlackTheme, 211);
    lv_obj_set_x(ui_btnBlackTheme, 200);
    lv_obj_set_y(ui_btnBlackTheme, -84);
    lv_obj_set_align(ui_btnBlackTheme, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBlackTheme, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBlackTheme, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBlackTheme, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBlackTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnBlackTheme, &ui_img_logo3_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnBlackTheme, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnBlackTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnBlackTheme, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_scrTheme);
    lv_obj_set_width(ui_Panel4, 797);
    lv_obj_set_height(ui_Panel4, 42);
    lv_obj_set_x(ui_Panel4, -1);
    lv_obj_set_y(ui_Panel4, 215);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x006592), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSaveTheme = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_btnSaveTheme, 136);
    lv_obj_set_height(ui_btnSaveTheme, 54);
    lv_obj_set_x(ui_btnSaveTheme, -328);
    lv_obj_set_y(ui_btnSaveTheme, 0);
    lv_obj_set_align(ui_btnSaveTheme, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSaveTheme, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSaveTheme, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnSaveTheme, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSaveTheme, lv_color_hex(0x00AAF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSaveTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_btnSaveTheme, lv_color_hex(0x00B0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_btnSaveTheme, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_btnSaveTheme, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_btnSaveTheme, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblLock2 = lv_label_create(ui_btnSaveTheme);
    lv_obj_set_width(ui_lblLock2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblLock2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblLock2, 1);
    lv_obj_set_y(ui_lblLock2, 0);
    lv_obj_set_align(ui_lblLock2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLock2, "Save");
    lv_obj_set_style_text_color(ui_lblLock2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblLock2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblLock2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWallpaper = lv_label_create(ui_scrTheme);
    lv_obj_set_width(ui_lblWallpaper, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWallpaper, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWallpaper, -224);
    lv_obj_set_y(ui_lblWallpaper, 69);
    lv_obj_set_align(ui_lblWallpaper, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWallpaper, "ENABLE WALLPAPER:");
    lv_obj_set_style_text_font(ui_lblWallpaper, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swEnableWallpaper = lv_switch_create(ui_scrTheme);
    lv_obj_set_width(ui_swEnableWallpaper, 74);
    lv_obj_set_height(ui_swEnableWallpaper, 47);
    lv_obj_set_x(ui_swEnableWallpaper, -10);
    lv_obj_set_y(ui_swEnableWallpaper, 67);
    lv_obj_set_align(ui_swEnableWallpaper, LV_ALIGN_CENTER);


    ui_rlrTime = lv_roller_create(ui_scrTheme);
    lv_roller_set_options(ui_rlrTime, "30 Secs\n1 Min\n2 Mins\n5 Mins\n10 Mins", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rlrTime, 326);
    lv_obj_set_height(ui_rlrTime, 85);
    lv_obj_set_x(ui_rlrTime, 91);
    lv_obj_set_y(ui_rlrTime, 142);
    lv_obj_set_align(ui_rlrTime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rlrTime, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_rlrTime, lv_color_hex(0x8CCBFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rlrTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRolllerTime = lv_label_create(ui_scrTheme);
    lv_obj_set_width(ui_lblRolllerTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRolllerTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRolllerTime, -222);
    lv_obj_set_y(ui_lblRolllerTime, 141);
    lv_obj_set_align(ui_lblRolllerTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRolllerTime, "WALLPAPER TIME:");
    lv_obj_add_flag(ui_lblRolllerTime, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lblRolllerTime, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnWhiteTheme, ui_event_btnWhiteTheme, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnBlackTheme, ui_event_btnBlackTheme, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSaveTheme, ui_event_btnSaveTheme, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swEnableWallpaper, ui_event_swEnableWallpaper, LV_EVENT_ALL, NULL);

}
