// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCRMAIN_H
#define UI_SCRMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMain
extern void ui_scrMain_screen_init(void);
extern void ui_scrMain_screen_destroy(void);
extern lv_obj_t * ui_scrMain;
extern lv_obj_t * ui_Image2;
extern void ui_event_arcGrup1(lv_event_t * e);
extern lv_obj_t * ui_arcGrup1;
extern lv_obj_t * ui_lblGrup1Oran1;
extern lv_obj_t * ui_lblGrup1;
extern void ui_event_arcGrup2(lv_event_t * e);
extern lv_obj_t * ui_arcGrup2;
extern lv_obj_t * ui_lblGrup1Oran2;
extern lv_obj_t * ui_lblGrup2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_lblHexnetTechnology;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_lblLock;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_pnlGrupSicaklikResim1;
extern lv_obj_t * ui_lblPnlGrup1SicaklikDeger1;
extern lv_obj_t * ui_lblPnlGrup1Sicaklik1;
extern lv_obj_t * ui_lblPnlGrup1Sicaklik2;
extern lv_obj_t * ui_lblPnlGrup1SicaklikDeger2;
extern lv_obj_t * ui_pnlGrupSicaklikResim2;
extern lv_obj_t * ui_pnlOutputs;
extern lv_obj_t * ui_imgBluetoothConnected;
extern lv_obj_t * ui_lblVangoText;
extern lv_obj_t * ui_imgsconnected;
extern lv_obj_t * ui_imgsnotconnected;
extern lv_obj_t * ui_imgBluetoothNotConnected;
extern lv_obj_t * ui_imgWForecast;
extern lv_obj_t * ui_lblDateAndTime;
extern lv_obj_t * ui_pnlSensors;
extern lv_obj_t * ui_lblWeather;
extern lv_obj_t * ui_pnlConnectionLost;
extern lv_obj_t * ui_Label1;
extern void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_btnRGBColor;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button22;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

