// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCRPAGES_H
#define UI_SCRPAGES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrPages
extern void ui_scrPages_screen_init(void);
extern void ui_scrPages_screen_destroy(void);
extern lv_obj_t * ui_scrPages;
extern void ui_event_btnDims(lv_event_t * e);
extern lv_obj_t * ui_btnDims;
extern void ui_event_btnTemperatures(lv_event_t * e);
extern lv_obj_t * ui_btnTemperatures;
extern void ui_event_btnWaters(lv_event_t * e);
extern lv_obj_t * ui_btnWaters;
extern void ui_event_btnRGBs(lv_event_t * e);
extern lv_obj_t * ui_btnRGBs;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_lblHexnetTechnology6;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_lblLock6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

