// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_scrRGB_screen_init(void)
{
    ui_scrRGB = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrRGB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_scrRGB);
    lv_obj_set_width(ui_Panel3, 797);
    lv_obj_set_height(ui_Panel3, 42);
    lv_obj_set_x(ui_Panel3, -1);
    lv_obj_set_y(ui_Panel3, 215);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x006592), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_Button11, 136);
    lv_obj_set_height(ui_Button11, 54);
    lv_obj_set_x(ui_Button11, -328);
    lv_obj_set_y(ui_Button11, 0);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x00AAF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button11, lv_color_hex(0x00B0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button11, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblLock6 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_lblLock6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblLock6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblLock6, 1);
    lv_obj_set_y(ui_lblLock6, 0);
    lv_obj_set_align(ui_lblLock6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLock6, "Return");
    lv_obj_set_style_text_color(ui_lblLock6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblLock6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblLock6, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Colorwheel1 = lv_colorwheel_create(ui_scrRGB, true);
    lv_obj_set_width(ui_Colorwheel1, 330);
    lv_obj_set_height(ui_Colorwheel1, 330);
    lv_obj_set_x(ui_Colorwheel1, 7);
    lv_obj_set_y(ui_Colorwheel1, -17);
    lv_obj_set_align(ui_Colorwheel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Colorwheel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_arc_width(ui_Colorwheel1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRGBApply = lv_btn_create(ui_scrRGB);
    lv_obj_set_width(ui_btnRGBApply, 184);
    lv_obj_set_height(ui_btnRGBApply, 177);
    lv_obj_set_x(ui_btnRGBApply, 9);
    lv_obj_set_y(ui_btnRGBApply, -17);
    lv_obj_set_align(ui_btnRGBApply, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnRGBApply, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnRGBApply, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnRGBApply, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnRGBApply, lv_color_hex(0x00AAF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRGBApply, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_scrRGB);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 7);
    lv_obj_set_y(ui_Label5, -19);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "APPLY");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swRGBTurnON = lv_switch_create(ui_scrRGB);
    lv_obj_set_width(ui_swRGBTurnON, 100);
    lv_obj_set_height(ui_swRGBTurnON, 57);
    lv_obj_set_x(ui_swRGBTurnON, -297);
    lv_obj_set_y(ui_swRGBTurnON, -184);
    lv_obj_set_align(ui_swRGBTurnON, LV_ALIGN_CENTER);


    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Colorwheel1, ui_event_Colorwheel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRGBApply, ui_event_btnRGBApply, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swRGBTurnON, ui_event_swRGBTurnON, LV_EVENT_ALL, NULL);

}
