// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCRPANELSETTINGS_H
#define UI_SCRPANELSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrPanelSettings
extern void ui_scrPanelSettings_screen_init(void);
extern void ui_scrPanelSettings_screen_destroy(void);
extern lv_obj_t * ui_scrPanelSettings;
extern lv_obj_t * ui_Panel10;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_lblLock4;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_lblSettings2;
extern lv_obj_t * ui_pnlSaveConfigs;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_pbSaveConfigs;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

